name: Node.js Package
on:
  create:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - run: yarn install
      - run: yarn build
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          filename: 'plugin.zip'
          directory: ./dist
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/plugin.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
