name: Node.js Package
on:
  create:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - run: yarn install
      - run: yarn build
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/plugin.js
            dist/madoc-plugin.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
